language: node_js
node_js:
  - 10
cache: yarn
before_install:
  - rm -rf build
  - npm install -g yarn@latest
  - yarn --version
  - npm install -g ganache-cli@latest
  - ganache-cli --version
script:
  - yarn run lint
  - yarn run solhint
  - yarn run pretty-check
  - solium -d contracts/
  - yarn run coverage && cat ./coverage/lcov.info | coveralls
before_deploy:
  - yarn pack --filename build/dex-contracts-$TRAVIS_TAG.tgz
deploy:
  provider: s3
  access_key_id: ""
  secret_access_key: ""
  bucket: ""
  script: bash ci/deploy.sh
  on:
    tags: true
after_deploy:
  - >
    curl
      -X POST
      -F "token=$GITLAB_TOKEN"
      -F "ref=master"
      -F "variables[TAG]=$TRAVIS_TAG"
      https://gitlab.gnosisdev.com/api/v4/projects/$GITLAB_PROJECT/trigger/pipeline
